In [79]:
#import all the necessary libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
%matplotlib inline




In [80]:
#import warnings to ignore warnings
import warnings
warnings.filterwarnings('ignore')

In [81]:
#Read the file

data = pd.read_csv(r'HR_Dataset.xls')
data.head(4)

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   

   time_spend_company  Work_accident  left  promotion_last_5years  \
0                   3              0     1                      0   
1                   6              0     1                      0   
2                   4              0     1                      0   
3                   5              0     1                      0   

  Departments   salary  Emp_ID  
0        sales     low       1  
1        sales  medium       2  
2        sales  medium       3  
3        sales     low       4

In [82]:
#Understanding Categorical Values and Numerical values in the Attributes from the Dataset 
numerical = data.select_dtypes('number').columns
catagorical = data.select_dtypes('object').columns

print(f'Numerical Columns : {numerical}')
print(f'Catogotrical Columns : {catagorical}')





Numerical Columns : Index(['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident', 'left',
       'promotion_last_5years', 'Emp_ID'],
      dtype='object')
Catogotrical Columns : Index(['Departments ', 'salary'], dtype='object')


Encoding Catogorical Columns (Since we have Catagorical column values )

In [83]:
data = pd.get_dummies(data, columns = ['Departments ','salary'], drop_first = True)
data.head()


satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  Emp_ID  \
0                   3              0     1                      0       1   
1                   6              0     1                      0       2   
2                   4              0     1                      0       3   
3                   5              0     1                      0       4   
4                   3              0     1                      0       5   

   Departments _RandD  Departments _accounting  Departments _hr  \
0                   0                        0                0   
1                   0                        0                0   
2                   0                        0                0   
3                   0                        0                0   
4                   0                        0                0   

   Departments _management  Departments _marketing  Departments _product_mng  \
0                        0                       0                         0   
1                        0                       0                         0   
2                        0                       0                         0   
3                        0                       0                         0   
4                        0                       0                         0   

   Departments _sales  Departments _support  Departments _technical  \
0                   1                     0                       0   
1                   1                     0                       0   
2                   1                     0                       0   
3                   1                     0                       0   
4                   1                     0                       0   

   salary_low  salary_medium  
0           1              0  
1           0              1  
2           0              1  
3           1              0  
4           1              0

In [84]:

#Define the dependent and independent variables
y=data['left'] #dependent variable
x=data.drop(['left','Emp_ID'],axis=1)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
data.head()


satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  Emp_ID  \
0                   3              0     1                      0       1   
1                   6              0     1                      0       2   
2                   4              0     1                      0       3   
3                   5              0     1                      0       4   
4                   3              0     1                      0       5   

   Departments _RandD  Departments _accounting  Departments _hr  \
0                   0                        0                0   
1                   0                        0                0   
2                   0                        0                0   
3                   0                        0                0   
4                   0                        0                0   

   Departments _management  Departments _marketing  Departments _product_mng  \
0                        0                       0                         0   
1                        0                       0                         0   
2                        0                       0                         0   
3                        0                       0                         0   
4                        0                       0                         0   

   Departments _sales  Departments _support  Departments _technical  \
0                   1                     0                       0   
1                   1                     0                       0   
2                   1                     0                       0   
3                   1                     0                       0   
4                   1                     0                       0   

   salary_low  salary_medium  
0           1              0  
1           0              1  
2           0              1  
3           1              0  
4           1              0

In [85]:
#Implementing Logistic Regression using sklearn
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

Model Evaluation 

In [86]:
y_pred = model.predict(x_test)
print(f"intercept: {model.intercept_}")
print(f"coefficients: {model.coef_}")

intercept: [-0.78330517]
coefficients: [[-4.34553586  0.45272307 -0.35359979  0.00501286  0.25843013 -1.44154239
  -0.79393081 -0.51784955  0.18401246  0.39944717 -0.64672252  0.07489504
  -0.00614776  0.02480905  0.07630039  0.07200997  1.53099921  1.03555222]]


In [87]:
ConfusionMatrix = confusion_matrix(y_test, y_pred)
print(ConfusionMatrix)


[[2120  178]
 [ 432  270]]


In [88]:
#x_train.loc[3452,'satisfaction_level']

y_train.head(5)



7216     0
11127    0
1945     1
9287     0
7448     0
Name: left, dtype: int64

In [89]:
from cmath import exp


size = len(data)

perc = np.zeros(14999)

for i in range(size):
    #res =(-0.51325937)-(4.17147337e+00)*(data.loc[i,'satisfaction_level'])+(6.44669928e-02)*(data.loc[i,'last_evaluation'])-(2.82734065e-01)*(data.loc[i,'number_project'])+(3.99991093e-03)*(data.loc[i,'average_montly_hours'])+(2.64838262e-01)*(data.loc[i,'time_spend_company'])-(1.74537427e+00)*(data.loc[i,'Work_accident'])-(6.62230222e-01)*(data.loc[i,'promotion_last_5years'])-(5.43260596e-01)*(data.loc[i,'Departments _RandD'])+(8.65754982e-02)*(data.loc[i,'Departments _accounting'])+(3.20189394e-01)*(data.loc[i,'Departments _hr'])-(6.61176215e-01)*(data.loc[i,'Departments _management'])+(3.89593078e-02)*(data.loc[i,'Departments _marketing'])+(2.00472926e-02)*(data.loc[i,'Departments _product_mng'])+(1.09441711e-01)*(data.loc[i,'Departments _sales'])+(1.58208240e-01)*(data.loc[i,'Departments _support'])+(1.62719089e-01)*(data.loc[i,'Departments _technical'])+(1.35397941e+00)*(data.loc[i,'salary_low'])+(8.01593685e-01)*(data.loc[i,'salary_medium'])
    res =(-0.59143995)-(4.13222786)*(data.loc[i,'satisfaction_level'])+(0.15148958)*(data.loc[i,'last_evaluation'])-0.28796745*(data.loc[i,'number_project'])+(0.00415672)*(data.loc[i,'average_montly_hours'])+(0.24258173)*(data.loc[i,'time_spend_company'])-1.70204427*(data.loc[i,'Work_accident'])-0.65774787*(data.loc[i,'promotion_last_5years'])-0.58958349*(data.loc[i,'Departments _RandD'])+(0.08908541)*(data.loc[i,'Departments _accounting'])+(0.27885606)*(data.loc[i,'Departments _hr'])-0.62343821*(data.loc[i,'Departments _management'])+(0.0095753)*(data.loc[i,'Departments _marketing'])+(0.01166724)*(data.loc[i,'Departments _product_mng'])+(0.05417304)*(data.loc[i,'Departments _sales'])+(0.28066013)*(data.loc[i,'Departments _support'])+(0.24499242)*(data.loc[i,'Departments _technical'])+(1.37440331)*(data.loc[i,'salary_low'])+(0.80729629)*(data.loc[i,'salary_medium'])

    value=1/(1+ 2.71828**(-res))
    perc[i]=value

In [90]:

perc.max()

0.8999280563180209

In [91]:
please =np.zeros(size)
for i in range(size):
    if(perc[i]>=0.5):
        please[i]=1
    else:
        please[i]=0

    


In [92]:
please

array([1., 0., 1., ..., 1., 1., 1.])

In [93]:
ConfusionMatrix = confusion_matrix(y,please)
print(ConfusionMatrix)

[[10631   797]
 [ 2181  1390]]


In [94]:
data_new = data

data_new['odds'] = perc.tolist()
data.head()


satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  Emp_ID  \
0                   3              0     1                      0       1   
1                   6              0     1                      0       2   
2                   4              0     1                      0       3   
3                   5              0     1                      0       4   
4                   3              0     1                      0       5   

   Departments _RandD  ...  Departments _hr  Departments _management  \
0                   0  ...                0                        0   
1                   0  ...                0                        0   
2                   0  ...                0                        0   
3                   0  ...                0                        0   
4                   0  ...                0                        0   

   Departments _marketing  Departments _product_mng  Departments _sales  \
0                       0                         0                   1   
1                       0                         0                   1   
2                       0                         0                   1   
3                       0                         0                   1   
4                       0                         0                   1   

   Departments _support  Departments _technical  salary_low  salary_medium  \
0                     0                       0           1              0   
1                     0                       0           0              1   
2                     0                       0           0              1   
3                     0                       0           1              0   
4                     0                       0           1              0   

       odds  
0  0.537826  
1  0.141759  
2  0.508494  
3  0.213115  
4  0.549764  

[5 rows x 21 columns]